### ISSUE TITLE
Issue on first run

### ISSUE THREAD

**Issue by ClementRoyer** [dsternlicht/RESTool#107]
(edited post)
Hi,
Had this error trying to run RESTool:

## Error

![image](https://user-images.githubusercontent.com/40796663/78302398-feb43f80-753a-11ea-9e8c-e8a56a37c0b5.png)
![image](https://user-images.githubusercontent.com/40796663/78302570-5652ab00-753b-11ea-8572-a828ec21b599.png)

<details>

plain text :
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:495:7)
    at noopServiceWorkerMiddleware (C:\[...]\RESTool\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\[...]\RESTool\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\[...]\RESTool\node_modules\express\lib\router\index.js:317:13)
    at C:\[...]\RESTool\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\[...]\RESTool\node_modules\express\lib\router\index.js:335:12)
    at next (C:\[...]\RESTool\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\[...]\RESTool\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\[...]\RESTool\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\[...]\RESTool\node_modules\express\lib\router\index.js:317:13)
    at C:\[...]\RESTool\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\[...]\RESTool\node_modules\express\lib\router\index.js:335:12)
    at next (C:\[...]\RESTool\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\[...]\RESTool\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\[...]\RESTool\node_modules\express\lib\router\layer.js:95:5)

</details>

## Cause
This error occur because in my installation path I have a "$", my computer name is "$J0S{numbers}"/

## Work around
I installed RESTool just under my "c:/" and it work, the error is really due to the "$".

**Comment by ClementRoyer** [comment]
I think I know why I have this error, my computer name is : "$J6S0{some numbers}",so my path is "C:\$J6S0[...]\Document\[...]". My computer name can be took as a variable ...

**Comment by ClementRoyer** [comment]
I also want to ask, is there any way to save a variable and re use it in the config.json (or js) ?

I mean it could usefull to retreive a token from a call and use this token in other request header.

(One cool way to implement this could be a page named "login", with a boolean "mustBeFilled", which wont give you access to the RESTool plateform before you logged in to your api)

**Comment by dsternlicht** [comment]
@ClementRoyer Yes, of course! Instead of using a `config.json`, you may use dynamic config `config.js` file. There you may add any logic you want! :)
