### ISSUE TITLE
Bug: Could not find config file.

### ISSUE THREAD

**Issue by JWebDev** [dsternlicht/RESTool#227]
Hi.
The tools does not starts out of the box.

**I get "Could not find config file."**

In console:
```
app.tsx:68 Could not load config file TypeError: _config__WEBPACK_IMPORTED_MODULE_7__ is not a function
    at loadConfig (app.tsx:40:1)
    at app.tsx:99:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
```
To Reproduce:
```
git clone
npm i
npm start
coped config-sample.json to /src/config.json to root and to src/config folder -> no effect.
```
Versions:
```
NodeJs: v18.12.0
Npm: 8.19.2
```

Thanks

**Comment by karstengresch** [comment]
Maybe the documentation could be enhanced a bit... e.g.

"Copy `./public/config-sample.json` to `./public/config.json` and adopt the settings to your liking."?

**Comment by dsternlicht** [comment]
@karstengresch done!
https://github.com/dsternlicht/RESTool/commit/cf7430862161a889e167c6053fa6517fb26f3eb0
